# Generated by Django 5.2.7 on 2025-11-13 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='apartment',
            field=models.ForeignKey(blank=True, help_text='Selecione o apartamento associado ao morador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_residents', to='core.apartment', unique=True, verbose_name='Apartamento'),
        ),
    ]
