# Generated by Django 5.2.7 on 2025-11-13 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('users', '0002_alter_person_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='apartment',
            field=models.OneToOneField(blank=True, help_text='Selecione o apartamento associado ao morador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_resident', to='core.apartment', verbose_name='Apartamento'),
        ),
    ]
