# Aqui listamos os serviços que serão utilizados
services:
  # Serviço do banco de dados PostgreSQL
  db:
    image: postgres:17-alpine
    container_name: porttusmart_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python -u manage.py runserver 0.0.0.0:8001
    container_name: web_app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
    volumes:
      - .:/app

volumes:
  postgres_data: