# Generated by Django 5.2.7 on 2025-11-13 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='recipients',
            field=models.ManyToManyField(related_name='received_communications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatários'),
        ),
        migrations.AddField(
            model_name='communication',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_communications', to=settings.AUTH_USER_MODEL, verbose_name='Remetente'),
        ),
        migrations.AddField(
            model_name='condominium',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condominium', to='core.address', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='condominium',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_condominiums', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='communication',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.condominium', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='core.condominium', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='finance',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finances', to='core.condominium', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='finance',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='notice',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='core.condominium', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocurrences', to='core.condominium', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_ocurrences', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por'),
        ),
        migrations.AddField(
            model_name='order',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.condominium', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário do Pedido'),
        ),
        migrations.AddField(
            model_name='order',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_orders', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.condominium', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Morador'),
        ),
        migrations.AddField(
            model_name='resident',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='core.apartment', verbose_name='Apartamento'),
        ),
        migrations.AddField(
            model_name='resident',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='core.condominium', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='resident',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_residents', to=settings.AUTH_USER_MODEL, verbose_name='Morador Principal'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.condominium', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por'),
        ),
        migrations.AddField(
            model_name='visit',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.apartment', verbose_name='Apartamento'),
        ),
        migrations.AddField(
            model_name='visit',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.condominium', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='visit',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_visits', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='core.condominium', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_visitors', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.visitor', verbose_name='Visitante'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('number', 'block', 'condominium'), name='unique_apartment_per_condo'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('plate', 'condominium'), name='unique_plate_per_condo'),
        ),
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('cpf', 'condominium')},
        ),
    ]
