# Generated by Django 5.2rc1 on 2025-06-09 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orders',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.person', verbose_name='Proprietário do Pedido'),
        ),
        migrations.AddField(
            model_name='orders',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_orders', to='core.person', verbose_name='Cadastrado por'),
        ),
        migrations.AddField(
            model_name='finance',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='core.person', verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='communication',
            name='recipients',
            field=models.ManyToManyField(related_name='received_communications', to='core.person', verbose_name='Destinatários'),
        ),
        migrations.AddField(
            model_name='communication',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.person', verbose_name='Remetente'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_apartments', to='core.person', verbose_name='Cadastrado por'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='residents',
            field=models.ManyToManyField(blank=True, help_text='Selecione os moradores que residem neste apartamento.', related_name='apartments', to='core.person', verbose_name='Moradores'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.person', verbose_name='Morador'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.person', verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_vehicles', to='core.person', verbose_name='Cadastrado por'),
        ),
        migrations.AddField(
            model_name='visit',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='core.apartment'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_visitors', to='core.person', verbose_name='Cadastrado por'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='core.visitor'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='visitors',
            field=models.ManyToManyField(related_name='visited_apartments', through='core.Visit', through_fields=('apartment', 'visitor'), to='core.visitor'),
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('order_code', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('visitor', 'apartment')},
        ),
    ]
