# Generated by Django 5.2.6 on 2025-10-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(verbose_name='Data e Hora de Fim'),
        ),
    ]
