# Generated by Django 5.2.7 on 2025-11-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='all_residents',
            field=models.BooleanField(default=False, help_text='Marque esta opção para enviar a comunicação para todos os moradores do condomínio.', verbose_name='Enviar para Todos os Moradores'),
        ),
    ]
