# Generated by Django 5.2.6 on 2025-10-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='tread',
            field=models.IntegerField(blank=True, null=True, verbose_name='Piso'),
        ),
    ]
