# Generated by Django 5.2.7 on 2025-11-05 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título da Ocorrência')),
                ('description', models.TextField(verbose_name='Descrição da Ocorrência')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('resolvida', 'Resolvida'), ('fechada', 'Fechada')], default='aberta', help_text='Selecione o status atual da ocorrência.', max_length=20, verbose_name='Status da Ocorrência')),
                ('date_reported', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ocorrência')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocurrences', to='core.condominium', verbose_name='Condomínio')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_ocurrences', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-date_reported'],
            },
        ),
    ]
