# Generated by Django 5.2.6 on 2025-10-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_apartment_tread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='entry_date',
            field=models.DateField(auto_now_add=True, default='2025-10-07', verbose_name='Data de Entrada'),
            preserve_default=False,
        ),
    ]
