# Generated by Django 5.2.7 on 2025-11-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_occurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='communication_type',
            field=models.CharField(choices=[('notice', 'Notice'), ('message', 'Message')], default='message', help_text='Selecione o tipo de comunicação.', max_length=20, verbose_name='Tipo de Comunicação'),
        ),
    ]
