# Generated by Django 5.2.6 on 2025-10-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_apartment_entry_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='apartment',
            name='unique_apartment_per_condo',
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('number', 'block', 'condominium'), name='unique_apartment_per_condo'),
        ),
    ]
